import json

from botelier.models.integration import IntegrationType

GUESTCENTRIC_INTEGRATION = {
    "slug": "guestcentric-crs",
    "name": "GuestCentric CRS",
    "description": "Connect to GuestCentric Central Reservation System for hotel search, availability, reservations, and guest management.",
    "logo_url": "/integrations/guestcentric-logo.png",
    "provider": "guestcentric",
    "auth_type": "basic_or_jwt",
    "documentation_url": "https://crs-api.guestcentric.net/documentation/developer.html",
    "auth_config": {
        "base_url": "https://crs-api.guestcentric.net/v1.0",
        "auth_methods": ["basic_auth", "jwt"],
        "jwt_login_endpoint": "/authentication/login",
        "jwt_refresh_endpoint": "/authentication/refresh",
        "jwt_check_endpoint": "/authentication/check_token",
        "jwt_max_lifetime_hours": 3,
        "basic_auth_query_params": ["apikey", "hotelId"],
        "auth_request_query_params": ["apikey"],
    },
    "required_fields": [
        {
            "key": "auth_method",
            "label": "Authentication Method",
            "type": "select",
            "options": ["basic_auth", "jwt"],
            "option_labels": {"basic_auth": "Basic Auth", "jwt": "JWT Token"},
            "description": "Choose Basic Auth for simpler setup or JWT for token-based auth",
            "required": True,
        },
        {
            "key": "username",
            "label": "Username",
            "type": "text",
            "placeholder": "Your GuestCentric username",
            "description": "GuestCentric API username. For Basic Auth, sent directly in the HTTP Basic Authorization header. For JWT auth, used to obtain a token via /authentication/login. Required for both auth methods.",
            "required": True,
        },
        {
            "key": "password",
            "label": "Password",
            "type": "password",
            "placeholder": "Your GuestCentric password",
            "description": "GuestCentric API password. For Basic Auth, sent directly in the HTTP Basic Authorization header. For JWT auth, used to obtain a token via /authentication/login. Required for both auth methods.",
            "required": True,
        },
        {
            "key": "apikey",
            "label": "API Key",
            "type": "text",
            "placeholder": "Your API key",
            "description": "API key provided by GuestCentric's integrations team. Sent as a query parameter on every request.",
            "required": True,
        },
        {
            "key": "hotelId",
            "label": "Hotel ID",
            "type": "text",
            "placeholder": "Hotel ID",
            "description": "Hotel ID GuestCentric assigned to this property. Stored as a connection setting (not a secret) and automatically added to every API request that needs it — it resolves {{hotel_id}} in endpoint paths and scopes Basic Auth requests to this hotel. Recommended for single-property connections on either auth method; leave blank only for JWT connections that intentionally span multiple hotels.",
            "required": False,
            "storage": "connection_config",
        },
    ],
    "endpoints": [
        {
            "id": "search_locations",
            "category": "Search",
            "name": "Search Locations",
            "description": "Look up countries, cities, or hotel names matching free text (minimum 3 characters).",
            "method": "GET",
            "path": "/search",
            "query_params": [{"key": "text", "value": "{{text}}", "required": True}],
            "variables": [
                {
                    "key": "text",
                    "type": "text",
                    "label": "Search Text",
                    "description": "Text to look up (minimum 3 characters). Case insensitive.",
                    "required": True,
                }
            ],
            "response_mapping": {
                "locations": "$",
                "first_country": "$[0].country",
                "first_city": "$[0].city",
                "first_hotel_name": "$[0].hotel",
            },
            "response_mapping_labels": {
                "locations": "All matching locations (countries/cities/hotels)",
                "first_country": "Country of the first matching result",
                "first_city": "City of the first matching result",
                "first_hotel_name": "Hotel name of the first matching result",
            },
        },
        {
            "id": "list_hotels",
            "category": "Hotels",
            "name": "List Hotels",
            "description": "List all hotels associated with the account (25 results per page).",
            "method": "GET",
            "path": "/hotels",
            "query_params": [
                {"key": "language", "value": "{{language}}", "required": False},
                {"key": "currency", "value": "{{currency}}", "required": False},
                {"key": "hotels", "value": "{{hotels}}", "required": False},
                {"key": "sap_code", "value": "{{sap_code}}", "required": False},
            ],
            "variables": [
                {
                    "key": "language",
                    "type": "text",
                    "label": "Language",
                    "description": "Response language code. Default: en_US",
                },
                {
                    "key": "currency",
                    "type": "text",
                    "label": "Currency",
                    "description": "Currency code for pricing. Default: EUR",
                },
                {
                    "key": "hotels",
                    "type": "text",
                    "label": "Hotel IDs",
                    "description": 'JSON array of hotel IDs to filter, e.g. ["cf5223be901bf"]. If omitted, all hotels under the API key are returned.',
                },
                {
                    "key": "sap_code",
                    "type": "text",
                    "label": "SAP Code",
                    "description": "SAP Access Code to filter by",
                },
            ],
            "response_mapping": {
                "hotels": "$.hotels",
                "total_pages": "$.total_pages",
                "number_of_hotels_found": "$.number_of_hotels_found",
                "price_type": "$.price_type",
            },
            "response_mapping_labels": {
                "hotels": "List of hotel objects",
                "total_pages": "Total number of result pages",
                "number_of_hotels_found": "Total number of hotels found",
                "price_type": "Price type shown (e.g. total_stay)",
            },
        },
        {
            "id": "search_hotels",
            "category": "Hotels",
            "name": "Search Hotels",
            "description": "Search hotels by availability criteria (check-in, check-out, and adults are mandatory).",
            "method": "GET",
            "path": "/hotels/search",
            "query_params": [
                {"key": "checkin", "value": "{{checkin}}", "required": True},
                {"key": "checkout", "value": "{{checkout}}", "required": True},
                {"key": "adults", "value": "{{adults}}", "required": True},
                {"key": "children", "value": "{{children}}", "required": False},
                {"key": "city", "value": "{{city}}", "required": False},
                {"key": "country", "value": "{{country}}", "required": False},
                {"key": "hotel_name", "value": "{{hotel_name}}", "required": False},
                {"key": "language", "value": "{{language}}", "required": False},
                {"key": "currency", "value": "{{currency}}", "required": False},
                {"key": "minimum_price", "value": "{{minimum_price}}", "required": False},
                {"key": "maximum_price", "value": "{{maximum_price}}", "required": False},
                {"key": "price_type", "value": "{{price_type}}", "required": False},
                {"key": "order_by", "value": "{{order_by}}", "required": False},
            ],
            "variables": [
                {
                    "key": "checkin",
                    "type": "date",
                    "label": "Check-in Date",
                    "description": "Check-in date (YYYY-MM-DD)",
                    "required": True,
                },
                {
                    "key": "checkout",
                    "type": "date",
                    "label": "Check-out Date",
                    "description": "Check-out date (YYYY-MM-DD)",
                    "required": True,
                },
                {
                    "key": "adults",
                    "type": "number",
                    "label": "Adults",
                    "description": "Number of adults per room",
                    "required": True,
                },
                {
                    "key": "children",
                    "type": "number",
                    "label": "Children",
                    "description": "Number of children per room",
                },
                {"key": "city", "type": "text", "label": "City", "description": "Filter by hotel city location"},
                {
                    "key": "country",
                    "type": "text",
                    "label": "Country",
                    "description": "Filter by hotel country location",
                },
                {
                    "key": "hotel_name",
                    "type": "text",
                    "label": "Hotel Name",
                    "description": "Filter by hotel name",
                },
                {
                    "key": "language",
                    "type": "text",
                    "label": "Language",
                    "description": "Response language code. Default: en_US",
                },
                {
                    "key": "currency",
                    "type": "text",
                    "label": "Currency",
                    "description": "Show prices in this currency (EUR or USD). Default: EUR",
                },
                {
                    "key": "minimum_price",
                    "type": "number",
                    "label": "Minimum Price",
                    "description": "Minimum price filter",
                },
                {
                    "key": "maximum_price",
                    "type": "number",
                    "label": "Maximum Price",
                    "description": "Maximum price filter",
                },
                {
                    "key": "price_type",
                    "type": "text",
                    "label": "Price Type",
                    "description": "Show prices per_night or total_stay. Default: total_stay",
                },
                {
                    "key": "order_by",
                    "type": "text",
                    "label": "Order By",
                    "description": "Order results by hotel_name or price. Default: price",
                },
            ],
            "response_mapping": {
                "hotels": "$.hotels",
                "total_pages": "$.total_pages",
                "number_of_hotels_found": "$.number_of_hotels_found",
                "price_min": "$.prices.minimum",
                "price_max": "$.prices.maximum",
            },
            "response_mapping_labels": {
                "hotels": "List of matching hotel objects (with rooms/rates)",
                "total_pages": "Total number of result pages",
                "number_of_hotels_found": "Total number of hotels found",
                "price_min": "Lowest price across results",
                "price_max": "Highest price across results",
            },
        },
        {
            "id": "hotel_rooms",
            "category": "Hotels",
            "name": "Hotel Rooms & Rates",
            "description": "Get available rooms, rates, promotions, and room-rate combinations for a hotel (check-in, check-out, and adults are mandatory).",
            "method": "GET",
            "path": "/hotels/{{hotel_id}}/rooms",
            "query_params": [
                {"key": "checkin", "value": "{{checkin}}", "required": True},
                {"key": "checkout", "value": "{{checkout}}", "required": True},
                {"key": "adults", "value": "{{adults}}", "required": True},
                {"key": "children", "value": "{{children}}", "required": False},
                {"key": "currency", "value": "{{currency}}", "required": False},
                {"key": "promotion_code", "value": "{{promotion_code}}", "required": False},
                {"key": "rate_plan_code", "value": "{{rate_plan_code}}", "required": False},
                {"key": "room_type_code", "value": "{{room_type_code}}", "required": False},
                {"key": "stricted", "value": "{{stricted}}", "required": False},
                {"key": "order_by", "value": "{{order_by}}", "required": False},
                {"key": "order", "value": "{{order}}", "required": False},
                {"key": "language", "value": "{{language}}", "required": False},
            ],
            "variables": [
                {
                    "key": "hotel_id",
                    "type": "text",
                    "label": "Hotel ID",
                    "description": "The hotel ID",
                    "required": True,
                },
                {
                    "key": "checkin",
                    "type": "date",
                    "label": "Check-in Date",
                    "description": "Check-in date (YYYY-MM-DD)",
                    "required": True,
                },
                {
                    "key": "checkout",
                    "type": "date",
                    "label": "Check-out Date",
                    "description": "Check-out date (YYYY-MM-DD)",
                    "required": True,
                },
                {
                    "key": "adults",
                    "type": "number",
                    "label": "Adults",
                    "description": "Number of adults per room",
                    "required": True,
                },
                {
                    "key": "children",
                    "type": "number",
                    "label": "Children",
                    "description": "Number of children per room",
                },
                {
                    "key": "currency",
                    "type": "text",
                    "label": "Currency",
                    "description": "Show prices in this currency (EUR or USD). Default: EUR",
                },
                {
                    "key": "promotion_code",
                    "type": "text",
                    "label": "Promotion Code",
                    "description": "Filter results to a specific promotion code",
                },
                {
                    "key": "rate_plan_code",
                    "type": "text",
                    "label": "Rate Plan Code",
                    "description": "Filter results to a single rate plan code (used to re-check the exact room + rate combination the caller selected)",
                },
                {
                    "key": "room_type_code",
                    "type": "text",
                    "label": "Room Type Code",
                    "description": "Filter results to a single room type code (used to re-check the exact room + rate combination the caller selected)",
                },
                {
                    "key": "stricted",
                    "type": "number",
                    "label": "Available Only",
                    "description": "Set to 1 to list only currently available rooms. Default: 0",
                },
                {
                    "key": "order_by",
                    "type": "text",
                    "label": "Order By",
                    "description": "Order results by hotel_name or price. Default: price",
                },
                {
                    "key": "order",
                    "type": "text",
                    "label": "Order",
                    "description": "Sort order: asc or desc. Default: desc",
                },
                {
                    "key": "language",
                    "type": "text",
                    "label": "Language",
                    "description": "Response language code. Default: en_US",
                },
            ],
            "response_mapping": {
                "rooms": "$.rooms",
                "rates": "$.rates",
                "room_rates": "$.room_rates",
                "first_room_type_code": "$.rooms[0].room_type_code",
                "first_room_name": "$.rooms[0].name",
                "first_rate_plan_code": "$.room_rates[0].rate_plan_code",
                "first_room_rate_code": "$.room_rates[0].room_rate_code",
                "first_total_price": "$.room_rates[0].total_price",
                "first_meal_plan_id": "$.room_rates[0].meal_plan_prices.included.id",
            },
            "response_mapping_labels": {
                "rooms": "Available room types",
                "rates": "Available rate plans",
                "room_rates": "Room + rate combinations with pricing",
                "first_room_type_code": "Room type code of the first room",
                "first_room_name": "Name of the first room",
                "first_rate_plan_code": "Rate plan code of the first room + rate combination",
                "first_room_rate_code": "Room + rate combination code of the first result (needed to book)",
                "first_total_price": "Total stay price of the first room + rate combination",
                "first_meal_plan_id": "Included meal plan ID of the first room + rate combination (needed to book)",
            },
        },
        {
            "id": "hotel_cancellation_policies",
            "category": "Hotels",
            "name": "Cancellation Policies",
            "description": "Get cancellation policies for one or more hotels.",
            "method": "GET",
            "path": "/hotels/cancellation_policies",
            "query_params": [
                {"key": "language", "value": "{{language}}", "required": False},
                {"key": "hotels", "value": "{{hotels}}", "required": True},
            ],
            "variables": [
                {
                    "key": "language",
                    "type": "text",
                    "label": "Language",
                    "description": "Response language code. Default: en_US",
                },
                {
                    "key": "hotels",
                    "type": "text",
                    "label": "Hotel IDs",
                    "description": 'JSON array of hotel IDs to get cancellation policies for, e.g. ["cf5223be901bf"]',
                    "required": True,
                },
            ],
            "response_mapping": {
                "policies": "$",
                "first_policy_id": "$[0].id",
                "first_policy_name": "$[0].name",
                "first_policy_teaser": "$[0].teaser",
                "first_policy_guarantee_text": "$[0].guarantee_text",
            },
            "response_mapping_labels": {
                "policies": "Array of cancellation policy objects",
                "first_policy_id": "ID of the first policy (needed to book)",
                "first_policy_name": "Name of the first policy",
                "first_policy_teaser": "Short description of the first policy",
                "first_policy_guarantee_text": "Guarantee description of the first policy",
            },
        },
        {
            "id": "hotel_guarantee_policies",
            "category": "Hotels",
            "name": "Guarantee Policies",
            "description": "Get guarantee policies for one or more hotels. Falls back to cancellation policies if no guarantee policy is configured.",
            "method": "GET",
            "path": "/hotels/guarantee_policies",
            "query_params": [
                {"key": "language", "value": "{{language}}", "required": False},
                {"key": "hotels", "value": "{{hotels}}", "required": True},
            ],
            "variables": [
                {
                    "key": "language",
                    "type": "text",
                    "label": "Language",
                    "description": "Response language code. Default: en_US",
                },
                {
                    "key": "hotels",
                    "type": "text",
                    "label": "Hotel IDs",
                    "description": 'JSON array of hotel IDs to get guarantee policies for, e.g. ["cf5223be901bf"]',
                    "required": True,
                },
            ],
            "response_mapping": {
                "policies": "$",
                "first_policy_name": "$[0].name",
                "first_policy_teaser": "$[0].teaser",
            },
            "response_mapping_labels": {
                "policies": "Array of guarantee (or fallback cancellation) policy objects",
                "first_policy_name": "Name of the first policy",
                "first_policy_teaser": "Short description of the first policy",
            },
        },
        {
            "id": "hotel_currencies",
            "category": "Hotels",
            "name": "Hotel Currencies",
            "description": "Get all available currencies for hotel pricing.",
            "method": "GET",
            "path": "/hotels/currencies",
            "variables": [],
            "response_mapping": {"currencies": "$"},
            "response_mapping_labels": {"currencies": "Array of available currency objects"},
        },
        {
            "id": "hotel_addons",
            "category": "Hotels",
            "name": "Hotel Addons",
            "description": "Get available reservation addons for a hotel (check-in, check-out, adults, and the hotels filter are mandatory).",
            "method": "GET",
            "path": "/hotels/{{hotel_id}}/addons",
            "query_params": [
                {"key": "checkin", "value": "{{checkin}}", "required": True},
                {"key": "checkout", "value": "{{checkout}}", "required": True},
                {"key": "adults", "value": "{{adults}}", "required": True},
                {"key": "children", "value": "{{children}}", "required": False},
                {"key": "language", "value": "{{language}}", "required": False},
                {"key": "room_type_code", "value": "{{room_type_code}}", "required": False},
                {"key": "stricted", "value": "{{stricted}}", "required": False},
                {"key": "hotels", "value": "{{hotels}}", "required": True},
            ],
            "variables": [
                {
                    "key": "hotel_id",
                    "type": "text",
                    "label": "Hotel ID",
                    "description": "The hotel ID",
                    "required": True,
                },
                {
                    "key": "checkin",
                    "type": "date",
                    "label": "Check-in Date",
                    "description": "Check-in date (YYYY-MM-DD)",
                    "required": True,
                },
                {
                    "key": "checkout",
                    "type": "date",
                    "label": "Check-out Date",
                    "description": "Check-out date (YYYY-MM-DD)",
                    "required": True,
                },
                {
                    "key": "adults",
                    "type": "number",
                    "label": "Adults",
                    "description": "Number of adults per room",
                    "required": True,
                },
                {
                    "key": "children",
                    "type": "number",
                    "label": "Children",
                    "description": "Number of children per room",
                },
                {
                    "key": "language",
                    "type": "text",
                    "label": "Language",
                    "description": "Response language code. Default: en_US",
                },
                {
                    "key": "room_type_code",
                    "type": "text",
                    "label": "Room Type Code",
                    "description": "Filter addons specific to this room type",
                },
                {
                    "key": "stricted",
                    "type": "number",
                    "label": "Available Only",
                    "description": "Set to 1 to list only currently available addons. Default: 0",
                },
                {
                    "key": "hotels",
                    "type": "text",
                    "label": "Hotel IDs",
                    "description": 'JSON array of hotel IDs, e.g. ["cf5223be901bf"]',
                    "required": True,
                },
            ],
            "response_mapping": {
                "addons": "$",
                "first_addon_name": "$[0].name",
                "first_addon_price": "$[0].unit_price",
            },
            "response_mapping_labels": {
                "addons": "Array of available addon objects",
                "first_addon_name": "Name of the first addon",
                "first_addon_price": "Unit price of the first addon",
            },
        },
        {
            "id": "book_reservation",
            "category": "Reservations",
            "name": "Book Reservation",
            "description": "Create a new reservation. Body is an array of reservation objects (one per room/hotel).",
            "method": "POST",
            "path": "/reservations/book",
            "body_template": {
                "reservations": [
                    {
                        "action": "new",
                        "status": "confirmed",
                        "checkin": "{{checkin}}",
                        "checkout": "{{checkout}}",
                        "number_of_rooms": "{{number_of_rooms}}",
                        "number_of_adults": "{{number_of_adults}}",
                        "number_of_children": "{{number_of_children}}",
                        "hotel": {
                            "id": "{{hotel_id}}",
                            "name": "{{hotel_name}}",
                            "hotel_reservations_email": "{{hotel_reservations_email}}",
                        },
                        "guest": {
                            "first_name": "{{guest_first_name}}",
                            "last_name": "{{guest_last_name}}",
                            "email": "{{guest_email}}",
                            "phone": "{{guest_phone}}",
                            "address": "{{guest_address}}",
                            "city": "{{guest_city}}",
                            "postal_code": "{{guest_postal_code}}",
                            "country": "{{guest_country}}",
                        },
                        "room_type": {"room_type_code": "{{room_type_code}}"},
                        "rate_plan": {"rate_plan_code": "{{rate_plan_code}}"},
                        "room_rate": {
                            "rate_plan_code": "{{rate_plan_code}}",
                            "room_rate_code": "{{room_rate_code}}",
                            "total_price": "{{total_price}}",
                            "daily_rates": [{"day": "{{checkin}}", "rate": "{{total_price}}"}],
                        },
                        "cancellation_policy": {"id": "{{cancellation_policy_id}}"},
                        "meal_plan": {
                            "id": "{{meal_plan_id}}",
                            "net": "{{meal_plan_net}}",
                            "tax": "{{meal_plan_tax}}",
                            "total": "{{meal_plan_total}}",
                        },
                    }
                ]
            },
            "variables": [
                {"key": "hotel_id", "type": "text", "label": "Hotel ID", "required": True},
                {"key": "hotel_name", "type": "text", "label": "Hotel Name", "required": True},
                {
                    "key": "hotel_reservations_email",
                    "type": "text",
                    "label": "Hotel Reservations Email",
                    "required": True,
                },
                {"key": "checkin", "type": "date", "label": "Check-in Date", "required": True},
                {"key": "checkout", "type": "date", "label": "Check-out Date", "required": True},
                {
                    "key": "number_of_rooms",
                    "type": "number",
                    "label": "Number of Rooms",
                    "default": 1,
                    "required": True,
                },
                {
                    "key": "number_of_adults",
                    "type": "number",
                    "label": "Adults",
                    "default": 1,
                    "required": True,
                },
                {"key": "number_of_children", "type": "number", "label": "Children", "default": 0},
                {
                    "key": "guest_first_name",
                    "type": "text",
                    "label": "Guest First Name",
                    "required": True,
                },
                {
                    "key": "guest_last_name",
                    "type": "text",
                    "label": "Guest Last Name",
                    "required": True,
                },
                {"key": "guest_email", "type": "text", "label": "Guest Email", "required": True},
                {"key": "guest_phone", "type": "text", "label": "Guest Phone", "required": True},
                {"key": "guest_address", "type": "text", "label": "Guest Address", "required": True},
                {"key": "guest_city", "type": "text", "label": "Guest City", "required": True},
                {
                    "key": "guest_postal_code",
                    "type": "text",
                    "label": "Guest Postal Code",
                    "required": True,
                },
                {"key": "guest_country", "type": "text", "label": "Guest Country", "required": True},
                {
                    "key": "room_type_code",
                    "type": "text",
                    "label": "Room Type Code",
                    "required": True,
                },
                {
                    "key": "rate_plan_code",
                    "type": "text",
                    "label": "Rate Plan Code",
                    "required": True,
                },
                {
                    "key": "room_rate_code",
                    "type": "text",
                    "label": "Room Rate Code",
                    "required": True,
                },
                {
                    "key": "total_price",
                    "type": "number",
                    "label": "Total Price",
                    "description": "Total stay price for this room",
                    "required": True,
                },
                {
                    "key": "cancellation_policy_id",
                    "type": "text",
                    "label": "Cancellation Policy ID",
                    "description": "From the Cancellation Policies endpoint",
                    "required": True,
                },
                {
                    "key": "meal_plan_id",
                    "type": "text",
                    "label": "Meal Plan ID",
                    "required": True,
                },
                {"key": "meal_plan_net", "type": "number", "label": "Meal Plan Net Price", "default": 0},
                {"key": "meal_plan_tax", "type": "number", "label": "Meal Plan Tax", "default": 0},
                {
                    "key": "meal_plan_total",
                    "type": "number",
                    "label": "Meal Plan Total",
                    "default": 0,
                },
            ],
            "response_mapping": {
                "reservations": "$.reservations",
                "crs_reservation_code": "$.reservations[0].crs_reservation_code",
                "hotel_reservation_code": "$.reservations[0].hotel_reservation_code",
                "status": "$.reservations[0].status",
            },
            "response_mapping_labels": {
                "reservations": "Array of created reservation objects",
                "crs_reservation_code": "CRS reservation code (primary confirmation reference)",
                "hotel_reservation_code": "Hotel-side reservation code",
                "status": "Reservation status (confirmed/cancelled)",
            },
        },
        {
            "id": "list_reservations",
            "category": "Reservations",
            "name": "List Reservations",
            "description": "List reservations, most recent first (25 per page by default).",
            "method": "GET",
            "path": "/reservations",
            "query_params": [
                {"key": "text", "value": "{{text}}", "required": False},
                {"key": "checkin", "value": "{{checkin}}", "required": False},
                {"key": "agent_email", "value": "{{agent_email}}", "required": False},
                {"key": "book_date", "value": "{{book_date}}", "required": False},
                {"key": "timezone", "value": "{{timezone}}", "required": False},
                {"key": "page", "value": "{{page}}", "required": False},
                {"key": "status", "value": "{{status}}", "required": False},
                {"key": "order_by", "value": "{{order_by}}", "required": False},
            ],
            "variables": [
                {
                    "key": "text",
                    "type": "text",
                    "label": "Search Text",
                    "description": "Search by CRS reservation code, hotel reservation code, guest name, or hotel name",
                },
                {
                    "key": "checkin",
                    "type": "date",
                    "label": "Check-in Date",
                    "description": "Filter by check-in date",
                },
                {
                    "key": "agent_email",
                    "type": "text",
                    "label": "Agent Email",
                    "description": "Filter by booking agent email",
                },
                {
                    "key": "book_date",
                    "type": "date",
                    "label": "Book Date",
                    "description": "Filter by the date the reservation was booked",
                },
                {
                    "key": "timezone",
                    "type": "text",
                    "label": "Timezone",
                    "description": "Timezone used to interpret book_date. Default: Europe/Lisbon",
                },
                {
                    "key": "page",
                    "type": "number",
                    "label": "Page",
                    "description": "Page number of results",
                },
                {
                    "key": "status",
                    "type": "text",
                    "label": "Status",
                    "description": "Filter by reservation status (confirmed or cancelled)",
                },
                {
                    "key": "order_by",
                    "type": "text",
                    "label": "Order By",
                    "description": "Order results by book_date or price. Default: book_date",
                },
            ],
            "response_mapping": {
                "reservations": "$.reservations",
                "page": "$.page",
                "total_pages": "$.total_pages",
            },
            "response_mapping_labels": {
                "reservations": "Array of matching reservation objects",
                "page": "Current page number",
                "total_pages": "Total number of result pages",
            },
        },
        {
            "id": "view_reservation",
            "category": "Reservations",
            "name": "View Reservation",
            "description": "Look up a reservation by its CRS reservation code.",
            "method": "GET",
            "path": "/reservations/view",
            "query_params": [
                {"key": "crs_reservation_code", "value": "{{crs_reservation_code}}", "required": True},
                {"key": "hotel_reservation_code", "value": "{{hotel_reservation_code}}", "required": False},
            ],
            "variables": [
                {
                    "key": "crs_reservation_code",
                    "type": "text",
                    "label": "CRS Reservation Code",
                    "description": "The CRS reservation code returned after booking",
                    "required": True,
                },
                {
                    "key": "hotel_reservation_code",
                    "type": "text",
                    "label": "Hotel Reservation Code",
                    "description": "Optional additional filter",
                },
            ],
            "response_mapping": {
                "crs_reservation_code": "$.reservations[0].crs_reservation_code",
                "hotel_reservation_code": "$.reservations[0].hotel_reservation_code",
                "status": "$.reservations[0].status",
                "checkin": "$.reservations[0].checkin",
                "checkout": "$.reservations[0].checkout",
                "guest_first_name": "$.reservations[0].guest.first_name",
                "guest_last_name": "$.reservations[0].guest.last_name",
            },
            "response_mapping_labels": {
                "crs_reservation_code": "CRS reservation code",
                "hotel_reservation_code": "Hotel-side reservation code",
                "status": "Reservation status (confirmed/cancelled)",
                "checkin": "Check-in date",
                "checkout": "Check-out date",
                "guest_first_name": "Guest first name",
                "guest_last_name": "Guest last name",
            },
        },
        {
            "id": "update_reservation",
            "category": "Reservations",
            "name": "Update Reservation",
            "description": "Update dates or guest counts on an existing reservation.",
            "method": "PUT",
            "path": "/reservations/update",
            "body_template": {
                "reservations": [
                    {
                        "action": "update",
                        "crs_reservation_code": "{{crs_reservation_code}}",
                        "hotel_reservation_code": "{{hotel_reservation_code}}",
                        "checkin": "{{checkin}}",
                        "checkout": "{{checkout}}",
                        "number_of_adults": "{{number_of_adults}}",
                        "number_of_children": "{{number_of_children}}",
                        "notes": "{{notes}}",
                    }
                ]
            },
            "variables": [
                {
                    "key": "crs_reservation_code",
                    "type": "text",
                    "label": "CRS Reservation Code",
                    "required": True,
                },
                {
                    "key": "hotel_reservation_code",
                    "type": "text",
                    "label": "Hotel Reservation Code",
                    "required": True,
                },
                {"key": "checkin", "type": "date", "label": "Check-in Date"},
                {"key": "checkout", "type": "date", "label": "Check-out Date"},
                {"key": "number_of_adults", "type": "number", "label": "Adults"},
                {"key": "number_of_children", "type": "number", "label": "Children"},
                {"key": "notes", "type": "text", "label": "Notes"},
            ],
            "response_mapping": {
                "reservations": "$.reservations",
                "status": "$.reservations[0].status",
            },
            "response_mapping_labels": {
                "reservations": "Array of updated reservation objects",
                "status": "Reservation status after the update",
            },
        },
        {
            "id": "modify_reservation",
            "category": "Reservations",
            "name": "Modify Reservation (Price Quote)",
            "description": "Request a modification quote (dates, room, etc). This returns updated pricing only — send a follow-up Update Reservation call to confirm the change.",
            "method": "PUT",
            "path": "/reservations/modify",
            "body_template": {
                "reservations": [
                    {
                        "action": "update",
                        "crs_reservation_code": "{{crs_reservation_code}}",
                        "hotel_reservation_code": "{{hotel_reservation_code}}",
                        "checkin": "{{checkin}}",
                        "checkout": "{{checkout}}",
                        "number_of_adults": "{{number_of_adults}}",
                        "number_of_children": "{{number_of_children}}",
                        "room_type": {"room_type_code": "{{room_type_code}}"},
                        "rate_plan": {"rate_plan_code": "{{rate_plan_code}}"},
                    }
                ]
            },
            "variables": [
                {
                    "key": "crs_reservation_code",
                    "type": "text",
                    "label": "CRS Reservation Code",
                    "required": True,
                },
                {
                    "key": "hotel_reservation_code",
                    "type": "text",
                    "label": "Hotel Reservation Code",
                    "required": True,
                },
                {"key": "checkin", "type": "date", "label": "Check-in Date"},
                {"key": "checkout", "type": "date", "label": "Check-out Date"},
                {"key": "number_of_adults", "type": "number", "label": "Adults"},
                {"key": "number_of_children", "type": "number", "label": "Children"},
                {"key": "room_type_code", "type": "text", "label": "Room Type Code"},
                {"key": "rate_plan_code", "type": "text", "label": "Rate Plan Code"},
            ],
            "response_mapping": {
                "reservations": "$.reservations",
                "status": "$.reservations[0].status",
            },
            "response_mapping_labels": {
                "reservations": "Array of reservation objects with the new quoted price",
                "status": "Reservation status",
            },
        },
        {
            "id": "cancel_reservation",
            "category": "Reservations",
            "name": "Cancel Reservation",
            "description": "Cancel a reservation.",
            "method": "POST",
            "path": "/reservations/cancel",
            "body_template": {
                "reservations": [
                    {
                        "crs_reservation_code": "{{crs_reservation_code}}",
                        "hotel_reservation_code": "{{hotel_reservation_code}}",
                        "status": "cancelled",
                    }
                ]
            },
            "variables": [
                {
                    "key": "crs_reservation_code",
                    "type": "text",
                    "label": "CRS Reservation Code",
                    "required": True,
                },
                {
                    "key": "hotel_reservation_code",
                    "type": "text",
                    "label": "Hotel Reservation Code",
                    "required": True,
                },
            ],
            "response_mapping": {
                "reservations": "$.reservations",
                "status": "$.reservations[0].status",
            },
            "response_mapping_labels": {
                "reservations": "Array of cancelled reservation objects",
                "status": "Reservation status (should be cancelled)",
            },
        },
        {
            "id": "resend_email",
            "category": "Reservations",
            "name": "Resend Confirmation Email",
            "description": "Re-send the reservation confirmation email to the guest and/or the hotel. At least one of send_to_guest / send_to_hotel must be true.",
            "method": "POST",
            "path": "/reservations/resendemail",
            "body_template": {
                "crs_reservation_code": "{{crs_reservation_code}}",
                "hotel_reservation_code": "{{hotel_reservation_code}}",
                "send_to_guest": "{{send_to_guest}}",
                "send_to_hotel": "{{send_to_hotel}}",
            },
            "variables": [
                {
                    "key": "crs_reservation_code",
                    "type": "text",
                    "label": "CRS Reservation Code",
                    "required": True,
                },
                {
                    "key": "hotel_reservation_code",
                    "type": "text",
                    "label": "Hotel Reservation Code",
                },
                {
                    "key": "send_to_guest",
                    "type": "boolean",
                    "label": "Send to Guest",
                    "default": True,
                },
                {
                    "key": "send_to_hotel",
                    "type": "boolean",
                    "label": "Send to Hotel",
                    "default": False,
                },
            ],
            "response_mapping": {"message": "$.message"},
            "response_mapping_labels": {"message": "Confirmation message describing where the email was sent"},
        },
    ],
}


def seed_guestcentric_integration(db_session):
    existing = db_session.query(IntegrationType).filter_by(slug="guestcentric-crs").first()

    if existing:
        existing.name = GUESTCENTRIC_INTEGRATION["name"]
        existing.description = GUESTCENTRIC_INTEGRATION["description"]
        existing.logo_url = GUESTCENTRIC_INTEGRATION["logo_url"]
        existing.provider = GUESTCENTRIC_INTEGRATION["provider"]
        existing.auth_type = GUESTCENTRIC_INTEGRATION["auth_type"]
        existing.documentation_url = GUESTCENTRIC_INTEGRATION["documentation_url"]
        existing.set_auth_config(GUESTCENTRIC_INTEGRATION["auth_config"])
        existing.set_required_fields(GUESTCENTRIC_INTEGRATION["required_fields"])
        existing.set_endpoints(GUESTCENTRIC_INTEGRATION["endpoints"])
        print(f"Updated GuestCentric CRS integration type: {existing.id}")
        db_session.commit()
        return existing
    else:
        integration = IntegrationType(
            slug=GUESTCENTRIC_INTEGRATION["slug"],
            name=GUESTCENTRIC_INTEGRATION["name"],
            description=GUESTCENTRIC_INTEGRATION["description"],
            logo_url=GUESTCENTRIC_INTEGRATION["logo_url"],
            provider=GUESTCENTRIC_INTEGRATION["provider"],
            auth_type=GUESTCENTRIC_INTEGRATION["auth_type"],
            documentation_url=GUESTCENTRIC_INTEGRATION["documentation_url"],
            is_enabled=True,
        )
        integration.set_auth_config(GUESTCENTRIC_INTEGRATION["auth_config"])
        integration.set_required_fields(GUESTCENTRIC_INTEGRATION["required_fields"])
        integration.set_endpoints(GUESTCENTRIC_INTEGRATION["endpoints"])

        db_session.add(integration)
        db_session.commit()
        print(f"Created GuestCentric CRS integration type: {integration.id}")
        return integration
